[tool.poetry]
name = "double-pendulum"
version = "0.1.0"
description = ""
authors = ["David Murray <david.murray16@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
scipy = "^1.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
